version: '3.9'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: moi@se
      POSTGRES_DB: "task-manager_app"
    networks:
      - taskmanager

networks:
  taskmanager:
